### ISSUE TITLE
Problem Compiling

### ISSUE THREAD

**Issue by Jorcor** [ritschmaster/w32bindkeys#2]
So I was looking into compiling this to mess with b3, and the directions for compiling using msys2 just don't work for me.

I also tried starting over with a fresh msys2 install and its still upset.

First, for the dependencies I had to also install the 'libtool' package to get autogen.sh to do anything at all.
Then once it runs further it gets down and I get an error about 'unknown type name 'DWORD' '

I'm real sure I'm just missing something stupid.

[autogen-output.txt](https://github.com/ritschmaster/w32bindkeys/files/4963617/autogen-output.txt)

**Comment by ritschmaster** [comment]
Sorry for missing out libtool in the Windows section! I will fix the README accordingly.

I guess you were using the instructions given on b3. For some reason I missed out to include mingw-w64-x86_64-gcc. Please install that one, use the MSYS2 MinGW 64-bit terminal, run `./autogen.sh clean && ./autogen.sh release` and you should be good to go.
