### ISSUE TITLE
How well does this work in comparisson to i3 on linux?

### ISSUE THREAD

**Issue by Sebastian-Nielsen** [ritschmaster/w32bindkeys#4]
How well does this work in comparisson to i3 on linux?

Can you show some screenshots?

**Comment by ritschmaster** [comment]
>How well does this work in comparisson to i3 on linux?

It doesn't. Compared to xbindkeys howeever it is ok for most normal ASCII key combinations.

> Can you show some screenshots?

As it should run in background, screenshots won't make any sense. But you may grab a release and have a look by yourself.
